### ISSUE TITLE
Change WML credentials to support IAM/Configure connection

### ISSUE THREAD

**Issue by rnostream** [IBMStreams/pypi.streamsx.pmml#9]
IBM Cloud
WML supports now IAM only. Legacy authorization is no more supported.

- Change model_feed  to support these IAM configuration properties
- Change configure_connection to support the IAM properties

IBM CP4D
Actual authentication and model storage is not very clear, we don't support fetching a model from WML with model_feed function on CP4D at moment.
Scoring functionality itself is supported at CP4D.

**Comment by swinkstn** [comment]
Is there a status on this?

**Comment by markheger** [comment]
Since PMML toolkit 3.0 the IAM authentication is supported.

https://www.ibm.com/support/knowledgecenter/SSCRJU_4.3.0/com.ibm.streams.tk20200930.doc/toolkits/dita/tk$com.ibm.streams.pmml/op$com.ibm.streams.pmml$WMLModelFeed.html#spldoc_operator__parameter__connectionConfiguration

You can create either create an application configuration and use the name in parameter `connection_configuration` of the `model_feed` function or pass the JSON from the service as dict to the same parameter.
